# Generated by Django 2.2.6 on 2021-05-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210426_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='В названии группы не должно содержаться нецензурной лексики и словосочетаний, призывающих к конфликту с другими группами лиц. Уместите название в 200 символов', max_length=200, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Постарайтесь не использовать нецензурную лексику,задевать власть, национальные меньшинства и других представителей флоры и фауны', verbose_name='Текст публикации'),
        ),
    ]
